### ISSUE TITLE
Add more info about members

### ISSUE THREAD

**Issue by vojtech-cerveny** [utituli/vkhcr_web#6]
in file `js/template.js`, add information about members - chairman, email, information about holy mass, address? 
[Old web](http://www.vkhcr.cz/clenove/)

**Comment by utituli** [comment]
Yes I definitely want same info about members as in old web but without address and Poznamka. Info should be in this order: web, predseda, mail and holy mass info.

**Comment by vojtech-cerveny** [comment]
Edited at #16
